# Generated by Django 2.2 on 2020-11-05 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductpromo',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
